services:
  - type: web
    name: patricio-turismo-web
    envVars:
      - key: JAVA_VERSION
        value: 17
    buildCommand: |
      echo "Iniciando build do Monorepo..."
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/src/main/resources/static
      cp -r frontend/dist/* backend/src/main/resources/static/
      cd backend
      ./mvnw clean package -DskipTests
    startCommand: java -jar backend/target/crud-0.0.1-SNAPSHOT.jar

databases:
  - name: patricio-db
    plan: free