services:
  - type: web
    name: patricio-turismo-web
    
    plan: free 
    envVars:
      - key: JAVA_VERSION
        value: 17
    
    buildCommand: |
      echo "Iniciando build do Monorepo..."
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/src/main/resources/static
      
      # --- CORREÇÃO AQUI ---
      # Mudamos de 'dist' para 'build'
      echo "Copiando arquivos do Frontend (da pasta 'build')..."
      cp -r frontend/build/* backend/src/main/resources/static/
      
      cd backend
      echo "Dando permissão de execução ao mvnw..."
      chmod +x mvnw
      echo "Construindo o Backend (Spring)..."
      ./mvnw clean package -DskipTests
      
    startCommand: java -jar backend/target/crud-0.0.1-SNAPSHOT.jar

databases:
  - name: patricio-db
    plan: free