services:
  - type: web
    name: patricio-turismo-web
    runtime: node
    plan: free 
    
    envVars:
      - key: JAVA_VERSION
        value: 17
    
    buildCommand: |
      echo "Iniciando build do Monorepo..."
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p backend/src/main/resources/static
      cp -r frontend/dist/* backend/src/main/resources/static/
      cd backend
      
      # --- CORREÇÃO AQUI ---
      # Adiciona permissão de execução ao script do Maven
      echo "Dando permissão de execução ao mvnw..."
      chmod +x mvnw
      # --- FIM DA CORREÇÃO ---
      
      echo "Construindo o Backend (Spring)..."
      ./mvnw clean package -DskipTests
      
    startCommand: java -jar backend/target/crud-0.0.1-SNAPSHOT.jar

databases:
  - name: patricio-db
    plan: free